print("                *                  ")
print("               ***                 ")
print("              *****                ")
print("             *******               ")
print("            *********              ")
print("           ***********             ")
print("          *************            ")
print("               **                  ")
print("               **                  ")
print("               **                  ")
print("          Merry Christmas          ")